#############################################
# RMIT University Vietnam
# Course: COSC2767|COSC2805 Systems Deployment and Operations
# Semester: 2025B
# Assessment: Assignment 2
# Author: Bui Viet Anh
# ID: s3988393
# Created  date: 14/09/2025
# Last modified: 18/09/2025
# Acknowledgement: None
#############################################

# ===== PROD variables =====
namespace: "{{ prod_namespace }}"
ingress_host: "{{ lookup('env','PROD_HOSTNAME') | default('auto', true) }}"

# Secrets for PROD (recommend storing with ansible-vault)
mongo_uri: "{{ mongo_uri_base }}"
