#############################################
# RMIT University Vietnam
# Course: COSC2767|COSC2805 Systems Deployment and Operations
# Semester: 2025B
# Assessment: Assignment 2
# Author: Bui Viet Anh
# ID: s3988393
# Created  date: 14/09/2025
# Last modified: 18/09/2025
# Acknowledgement: None
#############################################

---
# Validate required CLIs are available on the Jenkins host (local)
- name: Check aws, kubectl, and helm CLIs are available
  ansible.builtin.command: "{{ item.cmd }}"
  register: cli_check
  changed_when: false
  failed_when: cli_check.rc != 0
  loop:
    - { cmd: "aws --version" }
    - { cmd: "kubectl version --client" }
    - { cmd: "helm version --short" }

# Ensure kubeconfig is set for the EKS cluster (expects Jenkins has AWS CLI perms)
- name: Update kubeconfig for EKS cluster
  ansible.builtin.shell: |
    set -euo pipefail
    aws eks update-kubeconfig --region "{{ aws_region }}" --name "{{ eks_cluster }}"
  args:
    executable: /bin/bash
  changed_when: false
