#############################################
# RMIT University Vietnam
# Course: COSC2767|COSC2805 Systems Deployment and Operations
# Semester: 2025B
# Assessment: Assignment 2
# Author: Bui Viet Anh
# ID: s3988393
# Created  date: 14/09/2025
# Last modified: 18/09/2025
# Acknowledgement: None
#############################################

---
- hosts: mongodb
  gather_facts: false           # we can't gather facts until Python exists
  become: true

  pre_tasks:
    - name: Ensure python3 exists for Ansible modules
      raw: test -e /usr/bin/python3 || sudo dnf -y install python3

    - name: Gather facts after bootstrapping python
      setup:

  roles:
    - mongodb_host
