#############################################
# RMIT University Vietnam
# Course: COSC2767|COSC2805 Systems Deployment and Operations
# Semester: 2025B
# Assessment: Assignment 2
# Author: Bui Viet Anh
# ID: s3988393
# Created  date: 14/09/2025
# Last modified: 18/09/2025
# Acknowledgement: None
#############################################

---
# Configure cluster-level components & app config for the selected environment
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../group_vars/all.yml"
    - "{{ playbook_dir }}/../group_vars/{{ env | default('dev') }}.yml"
  vars:
    env: "{{ env | default('dev') }}"
  tasks:
    - name: Prepare CLIs and kubeconfig
      import_role:
        name: eks_tools

    - name: Install/upgrade ingress-nginx controller
      import_role:
        name: ingress_nginx

    - name: Apply K8s ConfigMap and Secret for this namespace
      import_role:
        name: k8s_config
