#############################################
# RMIT University Vietnam
# Course: COSC2767|COSC2805 Systems Deployment and Operations
# Semester: 2025B
# Assessment: Assignment 2
# Author: Bui Viet Anh
# ID: s3988393
# Created  date: 14/09/2025
# Last modified: 18/09/2025
# Acknowledgement: None
#############################################

---
- name: Add ingress-nginx Helm repo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Install/upgrade ingress-nginx
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    wait: true
    values:
      controller:
        service:
          type: LoadBalancer

- name: Patch ingress-nginx-controller service port to 8080
  kubernetes.core.k8s_json_patch:
    api_version: v1
    kind: Service
    namespace: ingress-nginx
    name: ingress-nginx-controller
    patch:
      - op: replace
        path: /spec/ports/0/port
        value: 8080
  ignore_errors: true
